### ISSUE TITLE
Suggestion: Single package verification, lib ignore, readelf extension

### ISSUE THREAD

**Issue by mettke** [matthiaskrgr/aurebuildcheck#2]
Hey,

I'm creating this issue 'cause I have a few suggestions for this script and I'm wondering whether you would consider merging if I add them. 

They aren't fully developed by now, but I have to do it over the next two weeks anyway and would consider adding them to your script if you are interested.

### default operation

The default operation would stay the same. If aurebuildcheck.sh is executed it would run over all installed packages and check them via ldd if there are missing libraries.

```bash
# Checks all locally installed packages via ldd
./aurebuildcheck.sh
```

### parameter for ldd and readelf check

In addition, if the parameter ```--ldd``` or ```--readelf``` is given, it will either use ldd or readelf to check the packages

```bash
# Checks all local installed packages via ldd
./aurebuildcheck.sh --ldd

# Checks all locally installed packages via readelf
./aurebuildcheck.sh --readelf
```

I have improved the readelf algorithm you removed with [5d0402d](https://github.com/matthiaskrgr/aurebuildcheck/commit/5d0402da5987a63193446c8d46174ddb15386bd0). It is now able to detect missing libraries. It is (IMHO) better than ldd 'cause ldd shows missing libraries which are incorrect

```bash
# get the needed libs
libs=`readelf -d "${file}" 2> /dev/null | awk '/NEEDED.*\[.*\]/''{print $5}' | awk  '{ gsub(/\[|\]/, "") ; print  }'`
# for each lib
IFS=$'\n'
for lib in ${libs} ; do
    # requried to track if the library was found or nod
    FOUND=false
    # check if lib is installed in the system folder. if not...
    if [ -z "$(ldconfig -p | grep ${lib})" ] && 
            [ ! -e "/usr/lib/${lib}" ] ; then
        (...)
    else 
        FOUND=true
    fi
done
```

### improved rpath

There are a few elf files which use "RUNPATH" instead of "RPATH". And there might also be multiple paths inside of the rpath separated by a colon.

```bash
# gets the rpath for the elf binary
rpaths=`readelf -d "${file}" | awk '/RPATH.*\[.*\]/''{print $5}' | awk  '{ gsub(/\[|\]/, "") ; print  }'`
if [ -z "${rpaths}" ]; then 
    rpaths=`readelf -d "${file}" | awk '/RUNPATH.*\[.*\]/''{print $5}' | awk  '{ gsub(/\[|\]/, "") ; print  }'`
fi
# sometimes there are multiple rpaths seperated by a colon. Seperating them by colon to create an array
IFS=':' read -r -a rpaths <<< "${rpaths}"
# for each rpath...
for rpath in "${rpaths[@]}"; do
    rpath=${rpath/'$ORIGIN'/$ORIGIN}
    # if the rpath leads to the library
    if [ -e "${rpath}/${lib}" ] ; then
        # set found to top
        FOUND=true
        # don't search anymore
        break
    fi
done   
```

### specify packages to check

I would like to add a parameter to specify which packages should be checked

```bash
# Checks only given packages via ldd
./aurebuildcheck.sh --packages dropbox discord
```

### specify libraries to ignore

I want to add a parameter to specify libraries which should not lead to an error. Probably only allowed when the packages parameter is used

```bash
# Checks only given packages via ldd ignoring ibQt5Core.so.5
./aurebuildcheck.sh --packages dropbox --ignore libQt5Core.so.5
```

```bash
arrayContainsElement () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}

for lib in ${libs} ; do
    IFS=$' '
    if [ -n "${IGNORE_VERIFY}" ] && arrayContainsElement "${lib}" ${IGNORE_VERIFY} ; then continue; fi
    (...)
done
```

### exit codes

Lastly, I want to add exit codes so that the script fails if one or more packages are not working. Probably also only when the packages parameter is used

**Comment by matthiaskrgr** [comment]
Hi,
I made a prototype of not-found libs finder for rust binaries (written in rust, also using ldd) however the repo is not published yet.
I am in the process of switching my main-machine to manjaro so I might be able to play around with pacman again and might also port aurebuildcheck to rust (it should be easy to paralellize it so it can check several programs or files at the same time)

Back when I made this script I was using shell script because it was the only languages I could do this in. :)

**Comment by matthiaskrgr** [comment]
rust prototype can be found here: https://github.com/matthiaskrgr/aurebuildcheck-rs/tree/arch
(the "arch" branch is for arch linux).

It uses multiple cores while checking so on my system it was already ~2x faster than the shell script as long as I am not bottlenecked by IO.

Docs on how to get rust toolchain: https://www.rust-lang.org/en-US/install.html

**Comment by mettke** [comment]
Nice, the advantage of using rust is, that there is a pretty nice [command line argument parser](https://github.com/kbknapp/clap-rs) which might help. 

You, however, didn't mention my suggestions. I know my way around in rust and would offer to help. But I can also understand if you want to code the first version yourself

**Comment by matthiaskrgr** [comment]
Hi, I'm sorry for the delay.

> Checks all local installed packages via ldd
>./aurebuildcheck.sh --ldd

> Checks all locally installed packages via readelf
>./aurebuildcheck.sh --readelf

I'm fine with this.
Although I would love to do the checking-for-libs in pure rust I am not sure if we have the sufficient crates for this yet.

>There are a few elf files which use "RUNPATH" instead of "RPATH". And there might also be multiple paths inside of the rpath separated by a colon.

Sounds good to me.
Do you think it would make sense to be able to take enviromental LD_LIBRARY_PATH into account?

>specify packages to check

also sounds good to me.

>specify libraries to ignore

sounds good to me.
Would it make sense to ignore libraries on a larger scale via regex?
Something like ````--ignore "foo.so.*"```` or ````--ignore bar.so.3.*````

>exit codes
also sounds good to me. :)

**Comment by matthiaskrgr** [comment]
>Nice, the advantage of using rust is, that there is a pretty nice command line argument parser which might help.

Yes, and it is easy to achieve parallelism via rayon (already implemented) and it allows for a somewhat sane error handling :D


>You, however, didn't mention my suggestions. I know my way around in rust and would offer to help. 

This is great!

>But I can also understand if you want to code the first version yourself

I owe you an apology, I do not want to disregard your work on the shells script, I just think that bash programming is kind of a deadend here.
If I had known someone was planing to modify it I would have probably ported it to rust earlier.

I feel like I am done with the initial rust port of the script, feel free to modify as you want.

**Comment by mettke** [comment]
> I owe you an apology, I do not want to disregard your work on the shells script, I just think that bash programming is kind of a deadend here.
If I had known someone was planing to modify it I would have probably ported it to rust earlier.

Don't worry - I had to do the changes anyway 'cause I need the features myself. Happy that you like my suggestions. I have started developing and should have my first prototype (based on yours) up this evening

**Comment by mettke** [comment]
Closing for https://github.com/matthiaskrgr/aurebuildcheck-rs/pull/1
